def obter_nomes_professores():
    return [
        "A. C. Damasceno",
        "A. K. O. de Moraes",
        "A. V. de Brito",
        "A. F. de C. Medeiros",
        "A. P. P. Wyse",
        "A. Subramanian",
        "A. V. Rocha",
        "A. de A. Formiga",
        "A. J. B. dos Santos",
        "L. S. Barros",
        "A. J. de Souza",
        "B. J. de S. Pessoa",
        "B. P. Bruck",
        "C. M. V. Barros",
        "C. A. N. Machado",
        "C. E. C. F. Batista",
        "C. A. Pagot",
        "C. de A. Siebra",
        "D. C. B. G. Pereira",
        "D. R. D. Ricarte",
        "D. Omaia",
        "E. P. Bezerra",
        "E. M. S. de Medeiros",
        "E. G. dos Anjos",
        "E. M. Salvador",
        "F. A. G. Moreno",
        "F. M. Matos",
        "F. de A. C. Souto",
        "G. F. de S. Filho",
        "G. de O. Mattos",
        "G. E. da Silveira",
        "G. L. de S. Filho",
        "G. C. P. de Oliveira",
        "G. H. M. B. Motta",
        "H. S. da Silva",
        "H. L. D. de S. Cavalcante",
        "I. E. da Fonseca",
        "J. R. de Faria",
        "J. Sokolowski",
        "J. A. G. de Lima",
        "J. M. A. Massera",
        "J. A. Moreira",
        "K. D. V. Villacorta",
        "L. C. de Souza",
        "L. V. Batista",
        "L. dos S. Machado",
        "L. D. N. e Silva",
        "L. dos A. F. C. Cabral",
        "M. F. de Amorim",
        "M. D. dos Santos",
        "N. C. Q. Lino",
        "R. de G. N. Filho",
        "R. Kulesza",
        "R. Q. do Nascimento",
        "R. A. C. Altafim",
        "R. A. P. Altafim",
        "S. de C. Bezerra",
        "T. A. Simoes",
        "T. L. B. Junior",
        "T. P. do Nascimento",
        "T. G. do Rego",
        "T. M. U. de Araujo",
        "V. Becker",
        "V. Nigam",
        "V. M. U. de Araujo",
        "Y. de A. M. Barbosa",
        "A. C. Cavalcanti",
        "ADRIANA CARLA DAMASCENO",
        "ALAN KELON OLIVEIRA DE MORAES",
        "ALISSON VASCONCELOS DE BRITO",
        "ALVARO FRANCISCO DE CASTRO MEDEIROS",
        "ANA PAULA PINTADO WYSE",
        "ANAND SUBRAMANIAN",
        "ANDREA VANESSA ROCHA",
        "ANDREI DE ARAUJO FORMIGA",
        "ANTONIO JOSE BONESS DOS SANTOS",
        "LUCIANO SALES BARROS",
        "APARECIDO JESUINO DE SOUZA",
        "BRUNO JEFFERSON DE SOUSA PESSOA",
        "BRUNO PETRATO BRUCK",
        "CAMILA MARA VITAL BARROS",
        "CARLOS ALBERTO NUNES MACHADO",
        "CARLOS EDUARDO COELHO FREIRE BATISTA",
        "CHRISTIAN AZAMBUJA PAGOT",
        "CLAUIRTON DE ALBUQUERQUE SIEBRA",
        "DANIELA COELHO BATISTA GUEDES PEREIRA",
        "DANIELLE ROUSY DIAS RICARTE",
        "DERZU OMAIA",
        "ED PORTO BEZERRA",
        "ELIZABET MARIA SPOHR DE MEDEIROS",
        "EUDISLEY GOMES DOS ANJOS",
        "EWERTON MONTEIRO SALVADOR",
        "FELIPE ANTONIO GARCIA MORENO",
        "FERNANDO MENEZES MATOS",
        "FRANCISCO DE ASSIS COUTINHO SOUTO",
        "GILBERTO FARIAS DE SOUSA FILHO",
        "GIORGIA DE OLIVEIRA MATTOS",
        "GLEDSON ELIAS DA SILVEIRA",
        "GUIDO LEMOS DE SOUZA FILHO",
        "GUSTAVO CHARLES PEIXOTO DE OLIVEIRA",
        "GUSTAVO HENRIQUE MATOS BEZERRA MOTTA",
        "HAMILTON SOARES DA SILVA",
        "HUGO LEONARDO DAVI DE SOUZA CAVALCANTE",
        "IGUATEMI EDUARDO DA FONSECA",
        "JAIRO ROCHA DE FARIA",
        "JAN SOKOLOWSKI",
        "JOSE ANTONIO GOMES DE LIMA",
        "JOSE MIGUEL AROZTEGUI MASSERA",
        "JOSILENE AIRES MOREIRA",
        "KELY DIANA VILLACORTA VILLACORTA",
        "LEANDRO CARLOS DE SOUZA",
        "LEONARDO VIDAL BATISTA",
        "LILIANE DOS SANTOS MACHADO",
        "LINCOLN DAVID NERY E SILVA",
        "LUCIDIO DOS ANJOS FORMIGA CABRAL",
        "MARDSON FREITAS DE AMORIM",
        "MOISES DANTAS DOS SANTOS",
        "NATASHA CORREIA QUEIROZ LINO",
        "RAIMUNDO DE GOUVEIA NOBREGA FILHO",
        "RAONI KULESZA",
        "ROBERTO QUIRINO DO NASCIMENTO",
        "RUY ALBERTO CORREA ALTAFIM",
        "RUY ALBERTO PISANI ALTAFIM",
        "SERGIO DE CARVALHO BEZERRA",
        "TATIANA ARAUJO SIMOES",
        "TEOBALDO LEITE BULHÕES JUNIOR",
        "TIAGO PEREIRA DO NASCIMENTO",
        "THAIS GAUDENCIO DO REGO",
        "TIAGO MARITAN UGULINO DE ARAUJO",
        "VALDECIR BECKER",
        "VIVEK NIGAM",
        "VITOR MENEGHETTI UGULINO DE ARAUJO",
        "YURI DE ALMEIDA MALHEIROS BARBOSA",
        "ANTONIO CARLOS CAVALCANTI"
    ]
print(obter_nomes_professores())